### ISSUE TITLE
Feature Request: Include checking for build depends 

### ISSUE THREAD

**Issue by AgentK7** [riptidewave93/LEDE-MR33#5]
Hi, i would recommend to create an check in the build.sh file which checks that the according packages for building LEDE are installed on the System. 

For Debian as example it would be the following packages: 
 git-core build-essential libssl-dev libncurses5-dev unzip gawk zlib1g-dev

**Comment by chunkeey** [comment]
This is really hard to do for every distro in the universe. Not everybody is using Debian or Ubuntu. Arch, Fedora, Slackware, etc. all have different packaging and tools. You are welcome to give it a try though. But please consider all those options. 

Check out https://github.com/openwrt/openwrt/commit/4943afd7818f56053231a5a7ae90e55da44f1f08 The MR33 was successfully up streamed. So future development will likely happen over there, since this "bringup repo" served its purpose.

**Comment by AgentK7** [comment]
Fair enough through, :)
